### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by rnlion** [ArchiveTeam/warrior-extras-installer#1]
On a brand new clean Warrior instance from archiveteam-warrior-v3.1-20200919.ova , installation of this project fails, apparently due to unmet/uninstallable dependencies (full install log attached):
```
Setting up libzstd1:amd64 (1.4.4+dfsg-3) ...
dpkg: dependency problems prevent configuration of zstd:
 zstd depends on libgcc-s1 (>= 3.0); however:
  Package libgcc-s1 is not installed.
```
This might be similar to this issue? https://github.com/f4exb/sdrangel/issues/524

Subsequent Warrior project runs will fail for missing wget+at; for example:
```
2020-11-18 08:04:55,981 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 47, in <module>
Exception: No usable Wget+At found.
2020-11-18 08:04:55,981 - seesaw.warrior - WARNING - Project nagi did not install correctly and we're ignoring this problem.
```

[2020-11-18 Warrior Extras Installer log.txt](https://github.com/ArchiveTeam/warrior-extras-installer/files/5558877/2020-11-18.Warrior.Extras.Installer.log.txt)

**Comment by chfoo** [comment]
Based on the logs, the packages gets fixed up eventually and wget-at does get installed correctly, but the actual project isn't using it because it's missing additional lua dependencies. The project readme files are wrong about compatibility, so they don't work in the Warrior VM. As I said in archiveteam/seesaw-kit#102, the projects can be run with Docker directly, not within the VM. This is problem is being worked on as a replacement is being made soon.
